apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kubernetes-dashboard
  repo: https://kubernetes.github.io/dashboard/
  includeCRDs: true
  valuesFile: values.yaml
  version: 6.0.7
  releaseName: prod 
  namespace: kd-prod

#patches:
#- path: deletesvc.yaml