apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubernetes-dashboard
    repo: https://kubernetes.github.io/dashboard/
    includeCRDs: true
    valuesFile: values.yaml
    version: 6.4.6
    releaseName: dev
    namespace: kd-dev
#patches:
#- path: deletesvc.yaml
