apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          dev: 'true'
      values:
        path: dev
  - clusters:
      selector:
        matchLabels:
          stage: 'true'
      values:
        path: stage
  - clusters:
      selector:
        matchLabels:
          prod: 'true'
      values:
        path: prod
  template:
    metadata:
      name: 'kd-{{values.path}}-{{name}}'
      annotations:
        ad.datadoghq.com/kubernetes-dashboard.logs: '[{"source":"kubernetes-dashboard","service":"kubernetes-dashboard"}]'
    spec:
      project: akp-helm-demo
      source:
        repoURL: https://github.com/dhpup/helm-demo-v2.git
        targetRevision: HEAD
        path: 'env/{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: 'kd-{{values.path}}'
      # syncPolicy:
      #   automated:
          # prune: true
        # syncOptions:
        # - CreateNamespace=true
